language: node_js
node_js: 8
sudo: required
dist: trusty
cache:
  apt: true
  directories:
  - node_modules
  - bower_components
  - "$HOME/.npm"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - npm install -g bower
  - bower install
script:
  # Run our tests with virtual X frame buffer, needed for the selenium browser tests
  - xvfb-run npm test
after_success: npm run coverage
